import type { Metadata } from "next";
import { Inter, Noto_Sans_Georgian } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import localFont from 'next/font/local'
import 'mapbox-gl/dist/mapbox-gl.css';


const inter = Inter({ subsets: ["latin"] });
const NotoSans = Noto_Sans_Georgian({ subsets: ['georgian'] })
const glaho = localFont({
  src: './fonts/bpg-glaho-webfont.woff2',
  display: 'swap',
  variable: '--font-glaho'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${NotoSans.className} `}>
        {/* <Header /> */}
        <div className=" flex justify-center ">
          {children}
        </div>
      </body>
    </html>
  );
}
